# These are the funding platforms that GitHub supports. You can add your usernames or URLs to these platforms.
github: aaron-pope-turner
patreon: YOUR_PATREON_USERNAME
open_collective: YOUR_OPEN_COLLECTIVE_USERNAME
ko_fi: YOUR_KO_FI_USERNAME
tidelift: YOUR_TIDELIFT_USERNAME
community_bridge: YOUR_COMMUNITY_BRIDGE_USERNAME
liberapay: YOUR_LIBERAPAY_USERNAME
issuehunt: YOUR_ISSUEHUNT_USERNAME
otechie: YOUR_OTECHIE_USERNAME
lfx_crowdfunding: YOUR_LFX_CROWDFUNDING_USERNAME
custom: # Replace with up to 4 custom URLs.
  - https://www.example.com/support-me
  - https://www.another-example.com/donate
